### ISSUE TITLE
Plugin is not working anymore since a few days

### ISSUE THREAD

**Issue by edautz** [bstrebel/pimatic-phone#8]
Since a few days I get:

Login failed for "xxxxxx@gmail.com", ICloudError: Misdirected Request [421]

For every ICloud device. Could it be Apple changes the ICloud API?

Kind regards,

Edautz

**Comment by bstrebel** [comment]
Thanks for the feedback. I also noticed the problem but wasn't sure if it is related to the API because it shows up after an power outage in my local environment with strange effects on some homeduino devices. I will check my icloud-promise helper module ...

**Comment by bstrebel** [comment]
I've done some investigation and found that several libraries (e.g. [find-my-iphone](https://github.com/matt-kruse/find-my-iphone/issues/25)  from @matt-kruse used by @Oitzu 's [pimatic-location-plugin](https://github.com/Oitzu/pimatic-location-plugin)) have problems to login to iCloud. Most probably Apple changed the API. The awesome [iCloud-API ](https://github.com/MauriceConrad/iCloud-API) from @MauriceConrad uses a much more sophisticated session and cookie handling which enables you to login. But unfortunately there are some problems with the FindMe service (session becomes invalid after appr. 15 minutes) so further research and reverse engineering seems to be required.
Until someone finds a reliable solution you can use the [iPhone App](https://appsto.re/nl/-hdTib.i) from @sweebee as a workaround if your Pimatic is reachable through the web. Since the reverse update API of pimatic-phone is compatible with pimatic-location this works fine. To avoid annoying error messages just set **_iCloudInterval_** to **_0_** and **_iCloudSuspended_** to _**Yes**_ in your PhoneDeviceIOS configuration.

**Comment by der-rudi** [comment]
Hi there,
On my pimatic the plugin started working again.
I would like to see some conformation from other users.

**Comment by edautz** [comment]
I had to reset my objects, but it looked promising that it works again!,

**Comment by bstrebel** [comment]
Many thanks to @der-rudi and @edautz for re-investigation and sharing the results. My iPhone devices are also working again after setting the iCloudInterval. And thanks to Apple for not having to spend more time reverse engineering an undocumented API...
